import { Product } from "../interface/product.interface";
import { ProductCategoryEnum } from "../enums/product-category.enum";

const mockImage = {
  public_id: "mock-product-image",
  secure_url:
    "https://img.magnific.com/vector-gratis/pantalla-realista-smartphone-diferentes-aplicaciones_52683-30241.jpg?semt=ais_hybrid&w=740&q=80",
};

/** Datos temporales para desarrollar y probar la UI sin depender de la API. */
export const initialProducts: Product[] = [
  {
    id: 1001,
    name: "Smartphone Nova X Pro",
    slug: "smartphone-nova-x-pro",
    alias: "Nova X Pro 5G",
    description: "Smartphone de alto rendimiento con cámara profesional y pantalla AMOLED.",
    category: ProductCategoryEnum.SMARTPHONES,
    brand: "NovaTech",
    model: "X Pro",
    specifications: [
      { label: "Pantalla", value: "6.7 pulgadas AMOLED" },
      { label: "Memoria", value: "256 GB" },
      { label: "RAM", value: "12 GB" },
    ],
    dimensions: { weight: 205, height: 16, width: 76, length: 163 },
    images: [mockImage],
    color: { name: "Azul noche", value: "#172554" },
    price: 899.99,
    stock: 100,
    maxCount: 5,
    minCount: 1,
    discount: 20,
    isActive: true,
    tenant_id: 1,
    average: 4.8,
    createdAt: new Date("2026-01-12"),
    modifiedAt: new Date("2026-02-03"),
  },
  {
    id: 1002,
    name: "Notebook Atlas Creator",
    slug: "notebook-atlas-creator",
    description: "Notebook versátil para creación de contenido, trabajo y entretenimiento.",
    category: ProductCategoryEnum.COMPUTING,
    brand: "Atlas",
    model: "Creator 14",
    specifications: [
      { label: "Procesador", value: "Core i7 de 13.ª generación" },
      { label: "Almacenamiento", value: "SSD 1 TB" },
    ],
    dimensions: { weight: 1450, height: 18, width: 224, length: 315 },
    images: [mockImage],
    price: 1499.5,
    stock: 25,
    maxCount: 3,
    minCount: 1,
    discount: 10,
    isActive: true,
    tenant_id: 1,
    average: 4.6,
    createdAt: new Date("2026-01-18"),
    modifiedAt: new Date("2026-02-05"),
  },
  {
    id: 1003,
    name: "Auriculares Pulse ANC",
    slug: "auriculares-pulse-anc",
    alias: "Pulse inalámbricos",
    description: "Auriculares inalámbricos con cancelación activa de ruido y batería extendida.",
    category: ProductCategoryEnum.OTHER,
    brand: "Pulse",
    model: "ANC 2",
    specifications: [{ label: "Autonomía", value: "38 horas" }],
    dimensions: { weight: 285, height: 19, width: 17, length: 20 },
    images: [mockImage],
    color: { name: "Blanco", value: "#f8fafc" },
    price: 129,
    stock: 5,
    maxCount: 4,
    minCount: 1,
    discount: 0,
    isActive: true,
    tenant_id: 1,
    average: 4.2,
    createdAt: new Date("2026-01-23"),
    modifiedAt: new Date("2026-02-07"),
  },
  {
    id: 1004,
    name: "Cafetera Barista Compact",
    slug: "cafetera-barista-compact",
    description: "Cafetera compacta para espresso con vaporizador de leche integrado.",
    category: ProductCategoryEnum.APPLIANCES,
    brand: "Barista",
    model: "Compact 300",
    specifications: [
      { label: "Potencia", value: "1350 W" },
      { label: "Presión", value: "15 bar" },
      { label: "Depósito", value: "1.5 L" },
      { label: "Material", value: "Acero inoxidable" },
    ],
    dimensions: { weight: 4200, height: 31, width: 20, length: 28 },
    images: [mockImage],
    color: { name: "Rojo", value: "#dc2626" },
    price: 249.9,
    stock: 0,
    maxCount: 2,
    minCount: 1,
    discount: 30,
    isActive: false,
    tenant_id: 1,
    average: 3.9,
    createdAt: new Date("2026-01-28"),
    modifiedAt: new Date("2026-02-08"),
  },
  {
    id: 1005,
    name: "Silla Ergo Office",
    slug: "silla-ergo-office",
    description: "Silla ergonómica con soporte lumbar ajustable para jornadas extensas.",
    category: ProductCategoryEnum.OFFICE,
    brand: "ErgoForm",
    model: "E-500",
    specifications: [
      { label: "Material", value: "Malla transpirable" },
      { label: "Altura", value: "Ajustable" },
    ],
    dimensions: { weight: 11200, height: 118, width: 66, length: 68 },
    images: [mockImage],
    price: 319,
    stock: 25,
    maxCount: 2,
    minCount: 1,
    discount: 0,
    isActive: true,
    tenant_id: 1,
    average: 4.4,
    createdAt: new Date("2026-02-01"),
    modifiedAt: new Date("2026-02-10"),
  },
  {
    id: 1006,
    name: "Kit Herramientas Pro 108",
    slug: "kit-herramientas-pro-108",
    description: "Kit completo de herramientas manuales para mantenimiento doméstico.",
    category: ProductCategoryEnum.TOOLS,
    brand: "Forge",
    model: "Pro 108",
    specifications: [{ label: "Piezas", value: "108" }],
    images: [mockImage],
    price: 189.75,
    stock: 100,
    maxCount: 6,
    minCount: 1,
    discount: 20,
    isActive: true,
    tenant_id: 1,
    average: 4.7,
    createdAt: new Date("2026-02-02"),
    modifiedAt: new Date("2026-02-11"),
  },
  {
    id: 1007,
    name: "Zapatillas Runner Flex",
    slug: "zapatillas-runner-flex",
    alias: "Runner Flex urbanas",
    description: "Zapatillas livianas para entrenamiento y uso urbano diario.",
    category: ProductCategoryEnum.SPORTS,
    brand: "Motion",
    model: "Flex 2",
    specifications: [
      { label: "Suela", value: "Goma EVA" },
      { label: "Talle", value: "36-45" },
      { label: "Uso", value: "Running y urbano" },
    ],
    dimensions: { weight: 620, height: 12, width: 22, length: 33 },
    images: [mockImage],
    color: { name: "Verde", value: "#16a34a" },
    price: 95,
    stock: 5,
    maxCount: 3,
    minCount: 1,
    discount: 10,
    isActive: true,
    tenant_id: 1,
    average: 4.1,
    createdAt: new Date("2026-02-04"),
    modifiedAt: new Date("2026-02-12"),
  },
  {
    id: 1008,
    name: "Consola GameBox One",
    slug: "consola-gamebox-one",
    description: "Consola de videojuegos con almacenamiento amplio y control inalámbrico.",
    category: ProductCategoryEnum.GAMES,
    brand: "GameBox",
    model: "One",
    specifications: [
      { label: "Almacenamiento", value: "1 TB" },
      { label: "Resolución", value: "4K UHD" },
    ],
    dimensions: { weight: 3200, height: 7, width: 25, length: 30 },
    images: [mockImage],
    color: { name: "Negro", value: "#111827" },
    price: 549.99,
    stock: 0,
    maxCount: 1,
    minCount: 1,
    discount: 0,
    isActive: false,
    tenant_id: 1,
    average: 4.9,
    createdAt: new Date("2026-02-05"),
    modifiedAt: new Date("2026-02-13"),
  },
  {
    id: 1009,
    name: "Lámpara Smart Home",
    slug: "lampara-smart-home",
    description: "Lámpara inteligente regulable compatible con rutinas y control remoto.",
    category: ProductCategoryEnum.HOME,
    brand: "Lumen",
    model: "Smart A19",
    specifications: [],
    images: [mockImage],
    price: 42.5,
    stock: 25,
    maxCount: 8,
    minCount: 1,
    discount: 30,
    isActive: true,
    tenant_id: 1,
    average: 3.7,
    createdAt: new Date("2026-02-06"),
    modifiedAt: new Date("2026-02-14"),
  },
  {
    id: 1010,
    name: "Mochila Travel 40L",
    slug: "mochila-travel-40l",
    description: "Mochila resistente para viajes cortos con compartimento para notebook.",
    category: ProductCategoryEnum.CAMPING,
    brand: "TrailPack",
    model: "Travel 40",
    specifications: [
      { label: "Capacidad", value: "40 litros" },
      { label: "Resistencia", value: "Tela impermeable" },
    ],
    dimensions: { weight: 980, height: 52, width: 32, length: 22 },
    images: [mockImage],
    price: 78,
    stock: 5,
    maxCount: 4,
    minCount: 1,
    discount: 0,
    isActive: false,
    tenant_id: 1,
    average: 4,
    createdAt: new Date("2026-02-07"),
    modifiedAt: new Date("2026-02-15"),
  },
];
