export enum CategorySpecsEnum {
  // Especificaciones para Smartphones
  SMARTPHONES_LANZAMIENTO = 'Lanzamiento',
  SMARTPHONES_SISTEMA_OPERATIVO = 'Sistema Operativo',
  SMARTPHONES_CHIPSET = 'Chipset',
  SMARTPHONES_PROCESADOR = 'Procesador',
  SMARTPHONES_GPU = 'GPU',
  SMARTPHONES_RAM = 'RAM',
  SMARTPHONES_ALMACENAMIENTO = 'Almacenamiento',
  SMARTPHONES_MEMORIA_AMPLIABLE = 'Memoria ampliable',
  SMARTPHONES_SIM = 'Sim',
  SMARTPHONES_RED_3G = 'Redes 3G',
  SMARTPHONES_RED_4G = 'Redes 4G',
  SMARTPHONES_RED_5G = 'Redes 5G',
  SMARTPHONES_WIFI = 'WiFi',
  SMARTPHONES_BLUETOOTH = 'Bluetooth',
  SMARTPHONES_CONECTIVIDAD = 'Conectividad',
  SMARTPHONES_SENSORES = 'Sensores',
  SMARTPHONES_PANTALLA = 'Pantalla',
  SMARTPHONES_RESOLUCION = 'Resolución',
  SMARTPHONES_DENSIDAD_PIXELES = 'Densidad de Píxeles',
  SMARTPHONES_PANTALLA_TIPO = 'Tipo Pantalla',
  SMARTPHONES_PANTALLA_FPS = 'FPS Pantalla',
  SMARTPHONES_PANTALLA_COLORES = 'Colores Pantalla',
  SMARTPHONES_CAMARA_PRINCIPAL = 'Cámara Principal',
  SMARTPHONES_CAMARA_FRONTAL = 'Cámara Frontal',
  SMARTPHONES_FUNCIONES_CAMARA = 'Funciones Cámara',
  SMARTPHONES_VIDEO = 'Video',
  SMARTPHONES_SONIDO = 'Sonido',
  SMARTPHONES_CONECTOR_AUDIO = 'Conector de audio',
  SMARTPHONES_CARGADOR = 'Cargador',
  SMARTPHONES_BATERIA = 'Batería',
  SMARTPHONES_CARGA_RAPIDA = 'Carga rápida',
  SMARTPHONES_CARGA_INALAMBRICA = 'Carga inalámbrica',
  SMARTPHONES_RESISTENCIA_AGUA = 'Resistencia al agua',
  SMARTPHONES_DIMENSIONES = 'Dimensiones',
  SMARTPHONES_PESO = 'Peso',
  SMARTPHONES_MATERIALES = 'Materiales',
  SMARTPHONES_COLOR = 'Color',

  // Especificaciones para Gaming
  GAMING_PLATAFORMA = 'Plataforma',
  GAMING_GENERO = 'Género',
  GAMING_DESARROLLADOR = 'Desarrollador',
  GAMING_DISTRIBUIDOR = 'Distribuidor',
  GAMING_FECHA_LANZAMIENTO = 'Fecha de lanzamiento',
  GAMING_MODOS_JUEGO = 'Modos de juego',
  GAMING_EDAD_RECOMENDADA = 'Edad recomendada',
}