@baseUrl = https://restful-api-v4.vercel.app/api/v1
@name = admin
@password = admin
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZW1haWwiOm51bGwsInJvbGUiOiJBRE1JTiIsInBpY3R1cmUiOm51bGwsImlhdCI6MTc3ODk4OTkxN30.gKa9uYa8qFlrwCZsfwdGTGKDbheEua626uvmjO0H9kA

###
# VERIFICATION
GET {{baseUrl}}/auth/verify
Authorization: Bearer {{token}}

###
# LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "name": "{{name}}",
  "password": "{{password}}"
}
